### PR TITLE
Fetch WEBM thumbnail_data by listing conversion directory

### LINKED ISSUE #690: TGS to WebM conversion fails when specifying > 33 FPS
The TGS to WebM conversion method expects lottieconverter to generate a file ending in `00.png`:
https://github.com/mautrix/telegram/blob/338a4d9761be565337e19739a953f4be25cccb63/mautrix_telegram/util/tgs_converter.py#L96
However, lottieconverter may generate files with more digits if the total amount of frames would exceed 99. If I get the Telegram docs right, a Sticker may have up to 3 seconds of animation, so to always stay below the "100 frame limit" one can at most specify 33 FPS for the conversion rate.

I don't know how desirable it actually is to convert stickers with 60FPS, but anyone trying that is currently confronted with a somewhat confusing `FileNotFoundError`.

### PR DESCRIPTION
**Pull request by sot-tech**
Fixes #690 

**NB**: used additional library [aiopath](https://github.com/alexdelorenzo/aiopath) for searching and reading thumbnail.
Hope, that it used correctly.

### CODE REVIEW

**Review by tulir — CHANGES_REQUESTED** [review]
That's a lot of dependencies for listing files (aiopath, aiofile, anyio, caio, sniffio). Just `os.listdir` is fine

**Comment by sumnerevans** [comment]
See also `pathlib.Path.glob`: https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob

**Comment by sot-tech** [comment]
Hello.

Both `Path.glob` and `glob.glob` can be used for this, but listing and read file are IO blocking operations, if we don't care this - i will make changes soon.
But in this case, i don't fully understand why lottieconverter and ffmpeg were put into async context. 🙄

**Comment by sot-tech** [comment]
Recheck, please.

**Comment by sot-tech** [comment]
@tulir Nice! But why [sort an array](https://github.com/mautrix/telegram/blob/28845b9daffe1ef0361c24fc5db46d6f1c8ccd94/mautrix_telegram/util/tgs_converter.py#L114) of files instead of just take a `min`?

**Comment by tulir** [comment]
Good point, fixed

**Pull request closed without merging**
